"""added assign_doctor_id field

Revision ID: d0f40954c609
Revises: f839dec2452a
Create Date: 2026-07-30 12:48:21.922882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f40954c609'
down_revision = 'f839dec2452a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_doctor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_doctor_id')

    # ### end Alembic commands ###
