"""add blood_group, ward, status to patients; add current_jti to users

Revision ID: ef6635439c0f
Revises: 69ab6e65ba8f
Create Date: 2026-08-13 14:47:39.539535

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "ef6635439c0f"
down_revision = "69ab6e65ba8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    patientstatus_enum = postgresql.ENUM(
        "Admitted", "Discharged", "Outpatient", name="patientstatus"
    )
    patientstatus_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blood_group", sa.String(length=5), nullable=True)
        )
        batch_op.add_column(sa.Column("ward", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("Admitted", "Discharged", "Outpatient", name="patientstatus"),
                nullable=False,
                server_default="Outpatient",
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("current_jti", sa.String(length=36), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("current_jti")

    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_column("status")
        batch_op.drop_column("ward")
        batch_op.drop_column("blood_group")

    postgresql.ENUM(name="patientstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
